name: Run scraper

on:
  schedule:
    - cron: '*/30 * * * *'   # runs every 30 minutes
  workflow_dispatch:         # also allows manual run

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install puppeteer

    - name: Run scraper
      run: node dihh.js

